apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openreport

resources:
  - namespace.yaml
  - persistent-volume.yaml
  - deployment.yaml

commonLabels:
  app: openreport
  version: v1

images:
  - name: kettustudio/openreport
    newTag: latest
