apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openreport-data-pvc
  namespace: openreport
  labels:
    app: openreport
    type: data-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 1Gi
